Repository energizer-develop/Y_FE_WIKI, pull requests merged in 2023-09, with the labels that each got.

#14 [#1] Feat Header Component
  src/App.tsx
  src/assets/icons/CommuteLogo.svg
  src/assets/icons/GalleryLogo.svg
  src/assets/icons/Logo.svg
  src/assets/icons/WikiLogo.svg
  src/components/Header.tsx
  src/types/custom.d.ts
Labels: feat, design

#18 [#17] Feat Navigation Container Component
  src/App.tsx
  src/components/NavigationContainer.tsx
  src/components/NavigationContainer/index.tsx
Labels: feat

#21 [#15] Publishing Modal
  package-lock.json
  package.json
  src/App.css
  src/assets/icons/closeButton.svg
  src/components/Header/index.tsx
  src/components/Modal/index.tsx
  src/constants/routes.ts
  src/index.css
  src/logo.svg
Labels: design

#25 [#16] Feat apply pretendard font
  src/index.tsx
  src/styles/global.ts
Labels: feat

#23 [#22] Fix React Modal StyledComponent Error
  src/App.tsx
  src/components/Modal/index.tsx
  src/index.css
  src/index.tsx
Labels: fix

#24 [#2] MainPage Component
  package-lock.json
  package.json
  public/images/1.png
  public/images/2.png
  public/images/3.png
  public/images/4.png
  src/components/Carousel/index.tsx
  src/components/a.tsx
  src/pages/Main.tsx
  src/pages/Main/index.tsx
  src/styles/a.tsx
Labels: feat

#29 [#9] Wiki Navigation Component
  src/App.tsx
  src/components/NavigationContainer/index.tsx
  src/components/NavigationWiki/index.tsx
  src/pages/Wiki/index.tsx
Labels: feat

#28 [#5] Gallery Navigation Component
  src/App.tsx
  src/components/NavigationGallery/index.tsx
  src/pages/Gallery/index.tsx
Labels: feat

#35 [#27] Implement Timer
  src/App.tsx
  src/assets/icons/commute.svg
  src/assets/icons/gallery.svg
  src/assets/icons/mainLogo.svg
  src/assets/icons/wiki.svg
  src/components/Header/index.tsx
  src/components/Modal/LiveClock.tsx
  src/components/Modal/index.tsx
  src/styles/global.ts
Labels: feat

#36 [#33] Implement useInterval
  src/components/Header/index.tsx
  src/components/Modal/LiveClock.tsx
  src/components/Modal/index.tsx
  src/constants/time.ts
  src/hooks/useInterval.ts
  src/utils/format.ts
Labels: feat

#38 [#37] Implement Stop Timer
  src/components/CommuteModal/LiveClock.tsx
  src/components/CommuteModal/index.tsx
  src/components/Header/index.tsx
  src/constants/time.ts
  src/hooks/useInterval.ts
  src/utils/format.ts
Labels: feat

#40 [#30] About Component Develop
  src/components/About/index.tsx
  src/components/Carousel/index.tsx
  src/pages/Main/index.tsx
Labels: feat

#41 [#6] Gallery Create - Modal
  src/components/UploadGallery/index.tsx
  src/pages/Gallery/index.tsx
Labels: feat

#45 [#42] Lottie Animation in MainPage Component
  package-lock.json
  package.json
  src/assets/lottieJSON/battery.json
  src/components/Common/MainLottie/index.tsx
  src/pages/Main/index.tsx
Labels: feat

#48 [#44] Implement Google Login
  package-lock.json
  package.json
  src/App.tsx
  src/apis/firebase.ts
  src/apis/index.ts
  src/constants/routes.ts
  src/pages/Login/index.tsx
Labels: feat

#52 [#6] Feat connection firebase
  src/apis/Gallery/index.tsx
  src/components/UploadGallery/index.tsx
Labels: feat

#54 [#53] Feat Firebase Storage
  src/apis/firebase.ts
Labels: feat

#49 [#49] Create Wiki Create
  package-lock.json
  package.json
  src/apis/Wiki/index.tsx
  src/constants/routes.ts
  src/pages/Wiki/index.tsx
  src/pages/WikiCreate/index.tsx
Labels: feat

#60 [#32] Responsive Design Header
  src/assets/icons/closeMenuButton.svg
  src/assets/icons/menu.svg
  src/components/Common/MainLottie/index.tsx
  src/components/CommuteModal/index.tsx
  src/components/Header/index.tsx
  src/styles/media.ts
Labels: design

#55 [#7] ReadGallery Component
  src/apis/Gallery/index.tsx
  src/assets/icons/deleteIcon.png
  src/components/ReadGallery/index.tsx
  src/components/UploadGalleryModal/index.tsx
  src/pages/Gallery/index.tsx
Labels: feat

#56 [#46] 404 Error Component Dev
  src/App.tsx
  src/assets/lottieJSON/lottie404.json
  src/components/Common/Lottie/index.tsx
  src/pages/NotFound/index.tsx
Labels: feat

#58 [#57] Loading Component Dev
  src/App.tsx
  src/assets/lottieJSON/loading.json
  src/components/Common/Loading/index.tsx
  src/components/Common/LoadingLottieContainer/index.tsx
Labels: feat

#61 [#32] modal, login page responsive design
  src/components/CommuteModal/LiveClock.tsx
  src/components/CommuteModal/index.tsx
  src/pages/Login/index.tsx
  src/styles/media.ts
Labels: design

#66 [#11] Create Wiki Read
  src/apis/Wiki/index.tsx
  src/pages/Wiki/index.tsx
Labels: feat

#68 remove: delete unusing wiki create component
  src/constants/routes.ts
  src/pages/WikiCreate/index.tsx
Labels: feat

#64 [#59] Mainpage Commute Component Develop
  package-lock.json
  package.json
  src/apis/index.ts
  src/components/CommuteList/index.tsx
  src/constants/time.ts
  src/pages/Main/index.tsx
  src/utils/format.ts
Labels: feat

#71 [#65] Gallery Component Responsive Design
  src/App.tsx
  src/apis/Gallery/index.tsx
  src/components/About/index.tsx
  src/components/Carousel/index.tsx
  src/components/Common/Loading/index.tsx
  src/components/Common/MainLottie/index.tsx
  src/components/CommuteList/index.tsx
  src/components/NavigationContainer/index.tsx
  src/components/NavigationGallery/index.tsx
  src/components/ReadGallery/index.tsx
  src/components/UploadGalleryModal/index.tsx
  src/pages/Calendar/index.tsx
  src/pages/Main/index.tsx
  src/pages/NotFound/index.tsx
  src/styles/global.ts
  src/styles/media.ts
Labels: design

#77 [#70] MainPage & NotFound Responsive
  src/App.tsx
  src/components/About/index.tsx
  src/components/Carousel/index.tsx
  src/components/Common/Loading/index.tsx
  src/components/Common/MainLottie/index.tsx
  src/components/CommuteList/index.tsx
  src/pages/Main/index.tsx
  src/pages/NotFound/index.tsx
Labels: design, style

#82 [#81] Calendar Responsive Design
  src/pages/Calendar/index.tsx
  src/styles/global.ts
Labels: design

#84 [#78] selected category
  src/components/NavigationGallery/index.tsx
Labels: design

#89 [#85] Mainpage TEXTS to CONST & responsive web applying
  src/components/About/index.tsx
  src/components/Carousel/index.tsx
  src/components/Common/MainLottie/index.tsx
  src/components/Section/aboutText.tsx
  src/components/Section/mainAbout.tsx
  src/components/Section/mainNotice.tsx
  src/components/Section/mainWorkTime.tsx
  src/constants/aboutwiki.ts
  src/constants/carouseltext.ts
  src/constants/maintext.ts
  src/pages/Main/index.tsx
Labels: feat, design, refactor

#90 [#86] Fix gallery page prview image error
  src/apis/Gallery/index.tsx
  src/components/Header/index.tsx
  src/components/ReadGallery/index.tsx
  src/components/UploadGalleryModal/index.tsx
  src/pages/Gallery/index.tsx
Labels: fix, refactor

#98 [#96] Fix wiki rendering
  src/apis/Wiki/index.tsx
  src/components/NavigationWiki/index.tsx
  src/components/Wiki/WikiContent.tsx
  src/components/Wiki/WikiCreate.tsx
  src/constants/wiki.ts
  src/pages/Wiki/index.tsx
Labels: fix, refactor

#102 [#100] Feat: Image Register Loading Animation & Refactor Gallery Component
  src/App.tsx
  src/apis/Gallery/index.tsx
  src/assets/lottieJSON/loadingImgRegister.json
  src/components/Common/Loading/index.tsx
  src/components/NavigationGallery/index.tsx
  src/components/ReadGallery/index.tsx
  src/components/UploadGalleryModal/index.tsx
  src/pages/Gallery/index.tsx
  src/pages/Wiki/index.tsx
  src/utils/deleteGalleryData.ts
Labels: feat, refactor

#103 [#26] Refactor constant, Styled naming
  src/App.tsx
  src/apis/Calendar/index.ts
  src/apis/User/index.tsx
  src/apis/WorkTime/index.ts
  src/assets/icons/loginIcon.svg
  src/components/CommuteModal/index.tsx
  src/components/Header/index.tsx
  src/constants/alert.ts
  src/constants/calendar.ts
  src/constants/common.ts
  src/constants/login.ts
  src/constants/time.ts
  src/pages/Calendar/index.tsx
  src/pages/Login/index.tsx
  src/utils/validate.ts
Labels: refactor

#109 [#107] rename: Carousel Image Name Change
  public/images/Slide1.png
  public/images/Slide2.png
  public/images/Slide3.png
  public/images/Slide4.png
  src/constants/carouseltext.ts
Labels: chore

#105 [#94] Mainpage Lottie Error & commuteList desgin revise
  src/components/Common/MainLottie/index.tsx
  src/components/CommuteList/index.tsx
  src/pages/Main/index.tsx
Labels: design, refactor

#108 [#106] favicon 추가
  public/favicon.ico
  public/index.html
  src/components/UploadGalleryModal/index.tsx
Labels: design

#104 [#101] Refactor Wiki
  src/components/NavigationWiki/index.tsx
  src/components/Wiki/WikiContent.tsx
  src/components/Wiki/WikiCreate.tsx
Labels: refactor

#111 [#110] Design Wiki Navigation Text
  src/components/NavigationWiki/index.tsx
  src/components/Wiki/WikiContent.tsx
  src/components/Wiki/WikiCreate.tsx
  src/pages/Wiki/index.tsx
Labels: design
